# Generated by Django 4.1.13 on 2026-01-28 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.IntegerField(choices=[(1, '入门'), (2, '进阶'), (3, '高阶'), (4, '专家')], default=1, verbose_name='难度等级'),
        ),
    ]
