from django.urls import path
from . import views

urlpatterns = [
    path("", views.lab_list_page, name="lab_list"),
    path("memory-poisoning/", views.memory_poisoning_page, name="memory_poisoning"),
    path("memory-poisoning/<slug:case_slug>/", views.memory_case_page, name="memory_case"),
    path("tool-poisoning/", views.tool_poisoning_page, name="tool_poisoning"),
    path("tool-poisoning/<slug:variant>/", views.tool_poisoning_variant_page, name="tool_poisoning_variant"),
    path("rag-poisoning/", views.rag_poisoning_page, name="rag_poisoning"),
    path("rag-poisoning/<slug:variant>/", views.rag_poisoning_variant_page, name="rag_poisoning_variant"),
    path("config/", views.llm_config_view, name="llm_config"),
    path("api/llm-test/", views.llm_test_api, name="llm_test_api"),
    path("api/memory-chat/", views.memory_chat_api, name="memory_chat_api"),
    path("api/memory-reset/", views.memory_reset_api, name="memory_reset_api"),
    path("api/memory-edit/", views.memory_edit_api, name="memory_edit_api"),
    path("api/tool-chat/", views.tool_chat_api, name="tool_chat_api"),
    path("api/rag-chat/", views.rag_chat_api, name="rag_chat_api"),
    path("rag-poisoning/seed/", views.rag_poisoning_seed, name="rag_poisoning_seed"),
    path("rag-poisoning/seed/<slug:variant>/", views.rag_poisoning_seed_variant, name="rag_poisoning_seed_variant"),
    path("rag-poisoning/clear/", views.rag_poisoning_clear, name="rag_poisoning_clear"),
    path("category/<slug:category_slug>/", views.lab_category_intro_page, name="lab_category_intro"),
    path("cswsh/", views.cswsh_lab_page, name="cswsh_lab"),
    path("cswsh/malicious/", views.cswsh_malicious_page, name="cswsh_malicious"),
    path("cswsh/dos/", views.dos_lab_page, name="dos_lab"),
    path("api/ws-connection-count/", views.ws_connection_count_api, name="ws_connection_count"),
    path("output-security/rce-eval/", views.rce_eval_lab_page, name="rce_eval_lab"),
    path("output-security/ssti-jinja/", views.ssti_jinja_lab_page, name="ssti_jinja_lab"),
    path("output-security/xss-render/", views.xss_render_lab_page, name="xss_render_lab"),
    path("api/output-security/rce-demo/", views.rce_eval_demo_api, name="rce_eval_demo_api"),
    path("api/output-security/ssti-demo/", views.ssti_jinja_demo_api, name="ssti_jinja_demo_api"),
    path("api/output-security/xss-demo/", views.xss_render_demo_api, name="xss_render_demo_api"),
    path("tool-security/rce/", views.tool_rce_lab_page, name="tool_rce_lab"),
    path("tool-security/ssrf/", views.tool_ssrf_lab_page, name="tool_ssrf_lab"),
    path("tool-security/xxe/", views.tool_xxe_lab_page, name="tool_xxe_lab"),
    path("tool-security/sqli/", views.tool_sqli_lab_page, name="tool_sqli_lab"),
    path("tool-security/yaml/", views.tool_yaml_lab_page, name="tool_yaml_lab"),
    path("tool-security/oauth/", views.tool_oauth_lab_page, name="tool_oauth_lab"),
    path("tool-security/browser/", views.tool_browser_lab_page, name="tool_browser_lab"),
    path("api/tool-security/fetch-url/", views.tool_ssrf_fetch_api, name="tool_ssrf_fetch_api"),
    path("api/tool-security/read-file/", views.tool_xxe_read_file_api, name="tool_xxe_read_file_api"),
    path("api/tool-security/query/", views.tool_sqli_query_api, name="tool_sqli_query_api"),
    path("api/tool-security/parse-yaml/", views.tool_yaml_parse_api, name="tool_yaml_parse_api"),
    path("api/tool-security/rce-invoke/", views.tool_rce_invoke_api, name="tool_rce_invoke_api"),
    path("api/tool-security/browser-url/", views.tool_browser_url_api, name="tool_browser_url_api"),
    path("api/tool-security/oauth-chat/", views.tool_oauth_chat_api, name="tool_oauth_chat_api"),
    path("mcp-security/indirect-pi/", views.mcp_indirect_lab_page, name="mcp_indirect_lab"),
    path("mcp-security/add-server/", views.mcp_ssrf_lab_page, name="mcp_ssrf_lab"),
    path("mcp-security/cross-tool/", views.mcp_cross_tool_lab_page, name="mcp_cross_tool_lab"),
    path("api/mcp-security/query-with-resource/", views.mcp_query_with_resource_api, name="mcp_query_with_resource_api"),
    path("api/mcp-security/add-server/", views.mcp_add_server_api, name="mcp_add_server_api"),
    path("api/mcp-security/cross-tool/", views.mcp_cross_tool_api, name="mcp_cross_tool_api"),
    # 进度、提示、收藏 API
    path("api/progress/complete/", views.lab_complete_api, name="lab_complete_api"),
    path("api/progress/hint/", views.lab_hint_api, name="lab_hint_api"),
    path("api/progress/favorite/", views.lab_favorite_api, name="lab_favorite_api"),
    path("api/progress/stats/", views.lab_stats_api, name="lab_stats_api"),
    # DVMCP 实战靶场
    path("dvmcp/", views.dvmcp_index_page, name="dvmcp_index"),
    path("dvmcp/<int:challenge_id>/", views.dvmcp_challenge_page, name="dvmcp_challenge"),
    path("api/dvmcp/status/", views.dvmcp_status_api, name="dvmcp_status_api"),
    path("api/dvmcp/config/", views.dvmcp_config_api, name="dvmcp_config_api"),
    path("api/dvmcp/llm-status/", views.dvmcp_llm_status_api, name="dvmcp_llm_status_api"),
    path("api/dvmcp/chat/", views.dvmcp_chat_api, name="dvmcp_chat_api"),
    path("api/dvmcp/tools/", views.dvmcp_tools_api, name="dvmcp_tools_api"),
    path("api/dvmcp/tool-call/", views.dvmcp_tool_call_api, name="dvmcp_tool_call_api"),
    path("api/dvmcp/resource-read/", views.dvmcp_resource_read_api, name="dvmcp_resource_read_api"),
    # System Prompt 泄露靶场
    path("system-prompt-leak/", views.system_prompt_leak_page, name="system_prompt_leak"),
    path("api/system-prompt-leak/chat/", views.system_prompt_leak_api, name="system_prompt_leak_api"),
    # 红队工具箱
    path("redteam/", views.redteam_index_page, name="redteam_index"),
    path("redteam/garak/", views.garak_scanner_page, name="garak_scanner"),
    path("redteam/mcpscan/", views.mcpscan_scanner_page, name="mcpscan_scanner"),
    path("redteam/jailbreak-payloads/", views.jailbreak_payloads_page, name="jailbreak_payloads"),
    path("api/redteam/garak/ollama-status/", views.garak_ollama_status_api, name="garak_ollama_status"),
    path("api/redteam/garak/scan/", views.garak_scan_api, name="garak_scan_api"),
    path("api/redteam/garak/scan-poll/", views.garak_scan_poll_api, name="garak_scan_poll"),
    path("api/redteam/mcpscan/scan/", views.mcpscan_scan_api, name="mcpscan_scan_api"),
    path("api/redteam/mcpscan/scan-poll/", views.mcpscan_scan_poll_api, name="mcpscan_scan_poll"),
    path("api/redteam/mcpscan/status/", views.mcpscan_status_api, name="mcpscan_status_api"),
    path("api/redteam/jailbreak/test/", views.jailbreak_test_api, name="jailbreak_test_api"),
    # 幻觉利用靶场
    path("hallucination/", views.hallucination_lab_page, name="hallucination_lab"),
    path("api/hallucination/chat/", views.hallucination_chat_api, name="hallucination_chat_api"),
    # 高级红队工具
    path("redteam/advanced-tools/", views.advanced_tools_page, name="advanced_tools"),
    # AIScan
    path("redteam/aiscan/", views.aiscan_page, name="aiscan_scanner"),
    path("api/redteam/aiscan/scan/", views.aiscan_scan_api, name="aiscan_scan_api"),
    path("api/redteam/aiscan/scan-poll/", views.aiscan_scan_poll_api, name="aiscan_scan_poll"),
    # 多模态安全
    path("multimodal/", views.multimodal_lab_page, name="multimodal_lab_default"),
    path("multimodal/<slug:variant>/", views.multimodal_lab_page, name="multimodal_lab"),
    path("api/multimodal/chat/", views.multimodal_chat_api, name="multimodal_chat_api"),
    path("api/multimodal/inject/", views.multimodal_inject_api, name="multimodal_inject_api"),
    path("api/multimodal/reset/", views.multimodal_reset_api, name="multimodal_reset_api"),
    # 高级安全靶场（基于前沿研究）
    path("advanced-lab/<slug:variant>/", views.advanced_lab_page, name="advanced_lab"),
    path("api/advanced-lab/chat/", views.advanced_lab_chat_api, name="advanced_lab_chat_api"),
]

