# Generated by Django 4.1.13 on 2026-01-28 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='题目名称')),
                ('description', models.TextField(verbose_name='题目描述')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='easy', max_length=10, verbose_name='难度')),
                ('flag', models.CharField(max_length=100, verbose_name='Flag')),
                ('points', models.IntegerField(default=10, verbose_name='积分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '靶场题目',
                'verbose_name_plural': '靶场题目',
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_flag', models.CharField(max_length=100, verbose_name='提交的Flag')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.challenge', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '解题记录',
                'verbose_name_plural': '解题记录',
            },
        ),
    ]
