# Generated by Django 4.1.13 on 2026-01-28 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('siliconflow', '硅基流动')], default='siliconflow', max_length=32, verbose_name='服务提供方')),
                ('api_base', models.URLField(default='https://api.siliconflow.cn/v1/chat/completions', max_length=255, verbose_name='API 地址')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key（仅存本地，勿提交到代码仓库）')),
                ('default_model', models.CharField(default='Qwen/Qwen3-VL-32B-Instruct', max_length=128, verbose_name='默认模型')),
                ('extra_headers', models.JSONField(blank=True, default=dict, verbose_name='额外 HTTP Header（可选，高级配置）')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '大模型配置',
                'verbose_name_plural': '大模型配置',
            },
        ),
        migrations.CreateModel(
            name='AgentMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario', models.CharField(default='memory_poisoning', max_length=64, verbose_name='场景标识')),
                ('data', models.JSONField(default=list, verbose_name='记忆内容（JSON 数组）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'Agent 记忆',
                'verbose_name_plural': 'Agent 记忆',
                'unique_together': {('user', 'scenario')},
            },
        ),
    ]
