# Generated by Django 4.1.13 on 2026-01-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_llmconfig_agentmemory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容（作为 RAG 知识）')),
                ('source', models.CharField(choices=[('internal', '内部文档'), ('external', '外部来源'), ('user_upload', '用户上传')], default='internal', max_length=32, verbose_name='来源')),
                ('is_poisoned', models.BooleanField(default=False, verbose_name='是否疑似恶意/投毒文档')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RAG 知识文档',
                'verbose_name_plural': 'RAG 知识文档',
            },
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('siliconflow', '硅基流动（云端）'), ('ollama', 'Ollama（本地）')], default='siliconflow', max_length=32, verbose_name='服务提供方'),
        ),
    ]
