# Generated by Django 4.1.13 on 2026-01-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0003_ragdocument_alter_llmconfig_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabCaseMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=128, unique=True, verbose_name="靶场标识（slug）")),
                ("title", models.CharField(blank=True, max_length=200, verbose_name="标题（可选覆盖）")),
                ("subtitle", models.TextField(blank=True, verbose_name="靶场简介（可选覆盖）")),
                ("scenario", models.TextField(blank=True, verbose_name="场景设定（可选覆盖）")),
                ("real_world", models.TextField(blank=True, verbose_name="真实世界示例（可选覆盖）")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "靶场文案配置",
                "verbose_name_plural": "靶场文案配置",
            },
        ),
    ]

# Generated by Django 4.1.13 on 2026-01-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_ragdocument_alter_llmconfig_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabCaseMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=128, unique=True, verbose_name='靶场标识（slug）')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='标题（可选覆盖）')),
                ('subtitle', models.TextField(blank=True, verbose_name='靶场简介（可选覆盖）')),
                ('scenario', models.TextField(blank=True, verbose_name='场景设定（可选覆盖）')),
                ('real_world', models.TextField(blank=True, verbose_name='真实世界示例（可选覆盖）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '靶场文案配置',
                'verbose_name_plural': '靶场文案配置',
            },
        ),
    ]
