# Generated by Django 4.1.13 on 2026-02-01 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0004_labcasemeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcasemeta',
            name='hint1',
            field=models.TextField(blank=True, verbose_name='提示1（轻度提示）'),
        ),
        migrations.AddField(
            model_name='labcasemeta',
            name='hint2',
            field=models.TextField(blank=True, verbose_name='提示2（中度提示）'),
        ),
        migrations.AddField(
            model_name='labcasemeta',
            name='hint3',
            field=models.TextField(blank=True, verbose_name='提示3（答案提示）'),
        ),
        migrations.CreateModel(
            name='LabProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_slug', models.CharField(max_length=128, verbose_name='靶场标识')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('hints_used', models.IntegerField(default=0, verbose_name='使用的提示数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '靶场进度',
                'verbose_name_plural': '靶场进度',
                'unique_together': {('user', 'lab_slug')},
            },
        ),
        migrations.CreateModel(
            name='LabFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_slug', models.CharField(max_length=128, verbose_name='靶场标识')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '靶场收藏',
                'verbose_name_plural': '靶场收藏',
                'unique_together': {('user', 'lab_slug')},
            },
        ),
    ]
