# Generated by Django 4.1.13 on 2026-02-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0005_labcasemeta_hint1_labcasemeta_hint2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI / 兼容 API'), ('ollama', 'Ollama（本地）'), ('siliconflow', '硅基流动'), ('deepseek', 'DeepSeek'), ('other', '其他')], default='siliconflow', max_length=32, verbose_name='服务提供方'),
        ),
    ]
